version = 1

[[annotations]]
	path = [
		"lib.typ",
		"typst.toml",
		"README.md"
	]
	precedence = "override"
	SPDX-FileCopyrightText = "2026 Ялла Нкардаз"
	SPDX-License-Identifier = "MIT"

[[annotations]]
	path = [
		".vscode/**",
		".gitignore",
		".gitattributes",
		"TODO.md"
	]

	SPDX-FileCopyrightText = "NONE"
	SPDX-License-Identifier = "CC0-1.0"
