[package]
name = "yn-book-template"
version = "1.0.0"
authors = ["Yalla Nkardaz <https://github.com/DemerNkardaz>"]
license = "MIT" # See REUSE.toml for licensing details
description = "A book project template"
repository = "https://github.com/DemerNkardaz/Typst-Book-Template"
keywords = ["book", "template"]
categories = ["book", "layout"]

[dependencies]
rustycure = "0.2.0"
rubby = "0.10.2"

[project-properties]
prefered-user-language = "ru"
