[origin]
template = ""
template-version = ""
created-at = ""
yal-version = ""

[[command]]
name = "make"
arguments = {--mode = []}
script = "/build/build.py"
exec = "python3"

[[command]]
name = "make print"
macros = "make --mode=print"
