[meta]
yal-min-version = "0.1.3"
post-commands = [
	"git init --initial-branch=main",
]
exclude = [
	".flake8",
	"typst.toml",
	"README.md",
	"LICENSE",
	"TODO.md"
]

[[fields]]
id             = "book-name"
type           = "text"
required       = true
default        = "{placeholder}"
is-folder-name = true

[[fields]]
id       = "book-author"
type     = "text"
required = false
default  = ""

[[fields]]
id       = "book-genre"
type     = "select"
required = false
options  = [
    "Fantasy",
		"Fiction",
    "Science Fiction",
		"Science Fantasy",
    "Horror",
    "Mystery",
    "Thriller",
    "Romance",
    "Historical",
    "Adventure",
    "Western",
    "Crime",
    "Drama",
    "Comedy",
    "Satire",
    "Dystopian",
    "Utopian",
    "Young Adult",
    "Children’s",
		"Autobiography",
]
default  = ""
allow-custom = true
min-cols = 2

[[fields]]
id       = "book-genres"
type     = "multi-select"
required = false
options  = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Romance",
    "Mystery",
    "Psychological",
    "Political",
    "Military",
    "Epic",
    "Dark",
    "Urban",
    "High Fantasy",
    "Low Fantasy",
		"Technofantasy",
    "Sword and Sorcery",
    "Space Opera",
    "Hard Science Fiction",
		"Science Fantasy",
    "Cyberpunk",
    "Steampunk",
    "Biopunk",
    "Post-Apocalyptic",
    "Supernatural",
    "Paranormal",
    "Gothic",
    "Survival",
    "Coming-of-Age",
    "Slice of Life",
    "Family",
    "Historical Fiction",
		"Historical Fantasy",
    "Philosophical",
    "Religious",
    "Mythological",
    "Noir",
    "Cozy",
    "Suspense",
    "Detective",
		"Novel",
		"Journal",
		"Diary",
		# Chinese
		"Wǔxiá",
		"Xiānxiá"
]
default  = []
allow-custom = true
min-cols = 2

[[fields]]
id						= "book-lang"
type					= "select"
required			= true
options				= [
	"en-US", "en-GB", "ru-RU", "uk-UA", "be-BY", "bg-BG", "kk-KZ",
	"de-DE", "de-CH", "fr-FR", "es-ES", "is-IS", "it-IT", "pt-BR",
	"ro-RO", "el-GR", "zh-CN", "ja-JP", "ko-KR"
]
default				= "en-US"
allow-custom	= true
min-cols = 2

[[fields]]
id				= "book-add-params"
type			= "boolean"
required	= false
default		= false

[[fields]]
id = "book-isbn"
type = "text"
required = false
default = "978-5-0000-0000-0"
show-if = "book-add-params"

[[fields]]
id = "book-issn"
type = "text"
required = false
default = "0000-0000"
show-if = "book-add-params"

[messages]
book-name.prompt      = "Enter book title"
book-name.placeholder = "Untitled book"
book-author.prompt    = "Enter author name"
book-author.placeholder = "Anonymous"

book-lang.prompt      = "Select book locale  in ISO-639, ISO-3166 format"
book-lang.option.label.en-US = "English (United States)"
book-lang.option.label.en-GB = "English (United Kingdom)"
book-lang.option.label.ru-RU = "Русский (Россия)"
book-lang.option.label.uk-UA = "Українська (Україна)"
book-lang.option.label.be-BY = "Беларуская (Беларусь)"
book-lang.option.label.bg-BG = "Български (България)"
book-lang.option.label.kk-KZ = "Қазақша (Қазақстан)"
book-lang.option.label.de-DE = "Deutsch (Deutschland)"
book-lang.option.label.de-CH = "Deutsch (Schweiz)"
book-lang.option.label.fr-FR = "Français (France)"
book-lang.option.label.es-ES = "Español (España)"
book-lang.option.label.is-IS = "Íslenska (Ísland)"
book-lang.option.label.it-IT = "Italiano (Italia)"
book-lang.option.label.pt-BR = "Português (Brasil)"
book-lang.option.label.ro-RO = "Românește (Romania)"
book-lang.option.label.el-GR = "Ελληνικά (Ελλαδα)"
book-lang.option.label.zh-CN = "中文 (中国大陆)"
book-lang.option.label.ja-JP = "日本語 (日本)"
book-lang.option.label.ko-KR = "한국어 (대한 고국)"

book-genre.prompt     = "Enter book genre"
book-genres.prompt     = "Select clarifying book genres"

book-add-params.prompt = "Fill additional parameters?"
book-isbn.prompt = "Enter ISBN"
book-issn.prompt = "Enter ISSN"

[messages.ru]
book-name.prompt      = "Введите название книги"
book-name.placeholder = "Книга без названия"
book-author.prompt    = "Введите имя автора"
book-author.placeholder = "Аноним"
book-lang.prompt      = "Выберите локализацию книги в формате ISO-639, ISO-3166"

book-genre.prompt     = "Введите жанр книги"
book-genre.option."Fantasy" = "Фэнтези"
book-genre.option."Fiction" = "Фантастика"
book-genre.option."Science Fiction" = "Научная фантастика"
book-genre.option."Science Fantasy" = "Научное фэнтези"
book-genre.option."Horror" = "Ужасы"
book-genre.option."Mystery" = "Мистика"
book-genre.option."Thriller" = "Триллер"
book-genre.option."Romance" = "Роман"
book-genre.option."Historical" = "Историческая проза"
book-genre.option."Adventure" = "Приключенческая проза"
book-genre.option."Western" = "Вестерн"
book-genre.option."Crime" = "Криминал"
book-genre.option."Drama" = "Драма"
book-genre.option."Comedy" = "Комедия"
book-genre.option."Satire" = "Сатира"
book-genre.option."Dystopian" = "Дистопия"
book-genre.option."Utopian" = "Утопия"
book-genre.option."Young Adult" = "Подростковая литература"
book-genre.option."Children’s" = "Детская литература"
book-genre.option."Autobiography" = "Автобиография"

book-genres.prompt     = "Выберите дополнительные жанры книги"
book-genres.option."Action" = "Действие"
book-genres.option."Adventure" = "Приключение"
book-genres.option."Comedy" = "Комедия"
book-genres.option."Drama" = "Драма"
book-genres.option."Romance" = "Романтика"
book-genres.option."Mystery" = "Мистика"
book-genres.option."Psychological" = "Психология"
book-genres.option."Political" = "Политика"
book-genres.option."Military" = "Военная литература"
book-genres.option."Epic" = "Эпическая литература"
book-genres.option."Dark" = "Тёмная литература"
book-genres.option."Urban" = "Городская литература"
book-genres.option."High Fantasy" = "Высокое фэнтези"
book-genres.option."Low Fantasy" = "Низкое фэнтези"
book-genres.option."Technofantasy" = "Технофэнтези"
book-genres.option."Sword and Sorcery" = "Меч и колдовство"
book-genres.option."Space Opera" = "Космическая опера"
book-genres.option."Hard Science Fiction" = "Твёрдая научная фантастика"
book-genres.option."Science Fantasy" = "Научное фэнтези"
book-genres.option."Cyberpunk" = "Киберпанк"
book-genres.option."Steampunk" = "Стимпанк"
book-genres.option."Biopunk" = "Биопанк"
book-genres.option."Post-Apocalyptic" = "Постапокалипсис"
book-genres.option."Supernatural" = "Сверхъестественное"
book-genres.option."Paranormal" = "Парадоксальное"
book-genres.option."Gothic" = "Готическая литература"
book-genres.option."Survival" = "Выживание"
book-genres.option."Coming-of-Age" = "История взросления"
book-genres.option."Slice of Life" = "Ломтик жизни"
book-genres.option."Family" = "Семейная литература"
book-genres.option."Historical Fiction" = "Историческая фантастика"
book-genres.option."Historical Fantasy" = "Историческое фэнтези"
book-genres.option."Philosophical" = "Философская литература"
book-genres.option."Religious" = "Религиозная литература"
book-genres.option."Mythological" = "Мифологическая литература"
book-genres.option."Noir" = "Нуар"
book-genres.option."Cozy" = "Кози"
book-genres.option."Suspense" = "Саспенс"
book-genres.option."Detective" = "Детектив"
book-genres.option."Novel" = "Роман"
book-genres.option."Journal" = "Журнал"
book-genres.option."Diary" = "Дневник"
book-genres.option."Wǔxiá" = "Уся"
book-genres.option."Xiānxiá" = "Сянься"

book-add-params.prompt = "Заполнить дополнительные свойства?"
book-isbn.prompt = "Введите ISBN"
book-issn.prompt = "Введите ISSN"

[[targets]]
file   = "/meta/book.yml"
format = "yaml"

[[targets.fields]]
value = "${UUID}"
key   = "book.uuid"

[[targets.fields]]
field = "book-name"
key   = "book.title"

[[targets.fields]]
field = "book-author"
key   = "author[0].name"

[[targets.fields]]
field = "book-lang"
key   = "property.locale"

[[targets.fields]]
value = "© {book-author}"
key   = "copyright.notice"

[[targets.fields]]
field = "book-genre"
fallback = "${NULL}"
key   = "property.genre"

[[targets.fields]]
field = "book-genres"
fallback = "${NULL}"
key   = "property.genres"

# [[targets.fields]]
# value = "${NULL}"
# key   = "book.series"

# [[targets.fields]]
# value = "${NULL}"
# key   = "book.cycle"

# [[targets.fields]]
# value = "${NULL}"
# key   = "book.volume-title"

# [[targets.fields]]
# value = "${NULL}"
# key   = "book.volume"

# [[targets.fields]]
# value = "${NULL}"
# key   = "book.description"

[[targets.fields]]
value = "${YEAR}"
key   = "date.year"

[[targets.fields]]
value = "${MONTH}"
key   = "date.month"

[[targets.fields]]
value = "${DAY}"
key   = "date.day"

[[targets.fields]]
field = "book-isbn"
key   = "property.ISBN"

[[targets.fields]]
field = "book-issn"
key   = "property.ISSN"
