# output-file-name: Моя книга
export-dir: export
color-conversion: true
open-after-build: false
png-ppi: 300
mode-default:
  ICC: sRGB_v4_ICC_preference_displayclass
  pdf-version: PDF 2.0
  # pdf-validator: PDF/A-4
  # pages: 1,2,6-
mode-print: 
  ICC: PSOcoated_v3
  pdf-version: PDF 2.0
  # pdf-validator: PDF/A-4
